### ISSUE TITLE
Built files missing when installing in pnpm monorepo

### ISSUE THREAD

**Issue by frederikvanhevel** [kreuzberg-dev/kreuzberg#241]
After installing @kreuzberg/node in my devcontainer i see the following warnings:
```
 WARN  Failed to create bin at /workspace/node_modules/.pnpm/node_modules/.bin/kreuzberg. ENOENT: no such file or directory, open '/workspace/node_modules/.pnpm/node_modules/@kreuzberg/node/dist/cli.js'
 WARN  Failed to create bin at /workspace/apps/processor/node_modules/.bin/kreuzberg. ENOENT: no such file or directory, open '/workspace/node_modules/.pnpm/@kreuzberg+node@4.0.0-rc.6/node_modules/@kreuzberg/node/dist/cli.js'
 WARN  Failed to create bin at /workspace/apps/processor/node_modules/.bin/kreuzberg. ENOENT: no such file or directory, open '/workspace/apps/processor/node_modules/@kreuzberg/node/dist/cli.js'
```

And the node_modules folder only contains javascript, no prebuilt binaries:
<img width="171" height="266" alt="Image" src="https://github.com/user-attachments/assets/652903fd-3075-4277-88c2-5b2ddb2452dd" />

**Comment by Goldziher** [comment]
yup. RC.10 will fix this

**Comment by Goldziher** [comment]
ok, please test RC.13 - released now.

**Comment by frederikvanhevel** [comment]
@Goldziher still no binaries installed on my machine. I'm running on Linux ARM64.

**Comment by Goldziher** [comment]
... Checking

**Comment by Goldziher** [comment]
@frederikvanhevel check rc.15 please

**Comment by piccinnigius** [comment]
> [@frederikvanhevel](https://github.com/frederikvanhevel) check rc.15 please

hi!, i've tried rc 16 with the following stack:

- nextjs 16.x
- pnpm / yarn / npm
- MacOS (M3)

I have the following errors:

<details>
<summary>Details</summary>

```sh
Error processing document GA IT.pdf Error: Failed to load Kreuzberg native bindings. Report this error and attach the logs/stack trace for investigation. Underlying error: Cannot find native binding. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.
    at parsePDF (src/server/actions/embeddings/worker.ts:441:37)
    at <unknown> (src/server/actions/embeddings/worker.ts:1003:19)
  439 |               return Buffer.from(arrayBuffer);
  440 |             })();
> 441 |         const r = await extractBytes(fileContent, mime_type);
      |                                     ^
  442 |         result = {
  443 |           kind: "kreuzberg",
  444 |           data: r, {
  [cause]: Error: Cannot find native binding. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.
      at parsePDF (src/server/actions/embeddings/worker.ts:441:37)
      at <unknown> (src/server/actions/embeddings/worker.ts:1003:19)
    439 |               return Buffer.from(arrayBuffer);
    440 |             })();
  > 441 |         const r = await extractBytes(fileContent, mime_type);
        |                                     ^
    442 |         result = {
    443 |           kind: "kreuzberg",
    444 |           data: r, {
    [cause]: Error: could not resolve "@kreuzberg/node-darwin-arm64" into a module
        at parsePDF (src/server/actions/embeddings/worker.ts:441:37)
        at <unknown> (src/server/actions/embeddings/worker.ts:1003:19)
      439 |               return Buffer.from(arrayBuffer);
      440 |             })();
    > 441 |         const r = await extractBytes(fileContent, mime_type);
          |                                     ^
      442 |         result = {
      443 |           kind: "kreuzberg",
      444 |           data: r, {
      [cause]: Error: Cannot find module './kreuzberg-node.darwin-arm64.node'
          at parsePDF (src/server/actions/embeddings/worker.ts:441:37)
          at <unknown> (src/server/actions/embeddings/worker.ts:1003:19)
        439 |               return Buffer.from(arrayBuffer);
        440 |             })();
      > 441 |         const r = await extractBytes(fileContent, mime_type);
            |                                     ^
        442 |         result = {
        443 |           kind: "kreuzberg",
        444 |           data: r, {
        code: 'MODULE_NOT_FOUND',
        [cause]: Error: Cannot find module '@kreuzberg/node-darwin-universal'
            at parsePDF (src/server/actions/embeddings/worker.ts:441:37)
            at <unknown> (src/server/actions/embeddings/worker.ts:1003:19)
          439 |               return Buffer.from(arrayBuffer);
          440 |             })();
        > 441 |         const r = await extractBytes(fileContent, mime_type);
              |                                     ^
          442 |         result = {
          443 |           kind: "kreuzberg",
          444 |           data: r, {
          code: 'MODULE_NOT_FOUND',
          [cause]: Error: Cannot find module './kreuzberg-node.darwin-universal.node'
              at parsePDF (src/server/actions/embeddings/worker.ts:441:37)
              at <unknown> (src/server/actions/embeddings/worker.ts:1003:19)
            439 |               return Buffer.from(arrayBuffer);
            440 |             })();
          > 441 |         const r = await extractBytes(fileContent, mime_type);
                |                                     ^
            442 |         result = {
            443 |           kind: "kreuzberg",
            444 |           data: r, {
            code: 'MODULE_NOT_FOUND'
          }
        }
      }
    }
  }
}
```

</details>

any suggestion?

**Comment by Goldziher** [comment]
check rc.18?

**Comment by Goldziher** [comment]
Fixed in v4.0.0-rc.19.

**Changes:**
- Added all 27 platform-specific packages as `optionalDependencies` in crates/kreuzberg-node/package.json
- Updated .npmignore to include npm/ directory in package distribution

The platform-specific .node binaries are now correctly included when installing in pnpm monorepos and Docker environments.

**Comment by piccinnigius** [comment]
hi @Goldziher , on rc 21 I still have the same issue, but the error output is a bit different :/

```bash
Error: Failed to load Kreuzberg native bindings. Report this error and attach the logs/stack trace for investigation. Underlying error: Cannot find native binding. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.
    at parsePDF (src/server/actions/embeddings/worker.ts:441:37)
    at <unknown> (src/server/actions/embeddings/worker.ts:1003:19)
  439 |               return Buffer.from(arrayBuffer);
  440 |             })();
> 441 |         const r = await extractBytes(fileContent, mime_type);
      |                                     ^
  442 |         result = {
  443 |           kind: "kreuzberg",
  444 |           data: r, {
  [cause]: Error: Cannot find native binding. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.
      at parsePDF (src/server/actions/embeddings/worker.ts:441:37)
      at <unknown> (src/server/actions/embeddings/worker.ts:1003:19)
    439 |               return Buffer.from(arrayBuffer);
    440 |             })();
  > 441 |         const r = await extractBytes(fileContent, mime_type);
        |                                     ^
    442 |         result = {
    443 |           kind: "kreuzberg",
    444 |           data: r, {
    [cause]: Error: could not resolve "@kreuzberg/node-darwin-arm64" into a module
        at parsePDF (src/server/actions/embeddings/worker.ts:441:37)
        at <unknown> (src/server/actions/embeddings/worker.ts:1003:19)
      439 |               return Buffer.from(arrayBuffer);
      440 |             })();
    > 441 |         const r = await extractBytes(fileContent, mime_type);
          |                                     ^
      442 |         result = {
      443 |           kind: "kreuzberg",
      444 |           data: r, {
      [cause]: Error: Cannot find module './kreuzberg-node.darwin-arm64.node'
          at parsePDF (src/server/actions/embeddings/worker.ts:441:37)
          at <unknown> (src/server/actions/embeddings/worker.ts:1003:19)
        439 |               return Buffer.from(arrayBuffer);
        440 |             })();
      > 441 |         const r = await extractBytes(fileContent, mime_type);
            |                                     ^
        442 |         result = {
        443 |           kind: "kreuzberg",
        444 |           data: r, {
        code: 'MODULE_NOT_FOUND',
        [cause]: Error: Cannot find module '@kreuzberg/node-darwin-universal'
            at parsePDF (src/server/actions/embeddings/worker.ts:441:37)
            at <unknown> (src/server/actions/embeddings/worker.ts:1003:19)
          439 |               return Buffer.from(arrayBuffer);
          440 |             })();
        > 441 |         const r = await extractBytes(fileContent, mime_type);
              |                                     ^
          442 |         result = {
          443 |           kind: "kreuzberg",
          444 |           data: r, {
          code: 'MODULE_NOT_FOUND',
          [cause]: Error: Cannot find module './kreuzberg-node.darwin-universal.node'
              at parsePDF (src/server/actions/embeddings/worker.ts:441:37)
              at <unknown> (src/server/actions/embeddings/worker.ts:1003:19)
            439 |               return Buffer.from(arrayBuffer);
            440 |             })();
          > 441 |         const r = await extractBytes(fileContent, mime_type);
                |                                     ^
            442 |         result = {
            443 |           kind: "kreuzberg",
            444 |           data: r, {
            code: 'MODULE_NOT_FOUND'
          }
        }
      }
    }
  }
}
```

**Comment by Goldziher** [comment]
hmm, its the optional dependencies. 

please verify these are installed by pnpm -- try adding the following to your `.npmrc`:

```txt
auto-install-peers=true
```

If this is working for you - i'll update the docs.

**Comment by Goldziher** [comment]
also - not recommended performance wise at all for node, but please test the wasm package (`@kreuzberg/wasm`) is working for you. Its substantially slower than native, but thats a known limitation of WASM, and it doesnt require any peer dependencies.

The alternative to this is to bundle all binaries in the package. The problem with this is that it makes the bundle much larger - unnecessarily.

**Comment by piccinnigius** [comment]
> auto-install-peers=true

Hi @Goldziher and happy new hear! sorry for bothering and late feedback but also with this (and wasm) doesn't work.
tested pnpm and npm without success.
stack is nextjs 16 on macos

```
An error occurred in a function passed to `after()`: Error: Error initializing Kreuzberg WASM module: Cannot find module './kreuzberg_wasm.js'
    at async (src/server/actions/embeddings/worker.ts:997:7)
   995 |   after(async () => {
   996 |     if (DOCUMENTS_PARSER === "kreuzberg") {
>  997 |       await initWasm();
       |       ^
   998 |       await enableOcr();
   999 |     }
  1000 |     for (const { id: job_id, document_id: document, document_type } of jobs) { {
  [cause]: Error: Cannot find module './kreuzberg_wasm.js'
      at async (src/server/actions/embeddings/worker.ts:997:7)
     995 |   after(async () => {
     996 |     if (DOCUMENTS_PARSER === "kreuzberg") {
  >  997 |       await initWasm();
         |       ^
     998 |       await enableOcr();
     999 |     }
    1000 |     for (const { id: job_id, document_id: document, document_type } of jobs) { {
    code: 'MODULE_NOT_FOUND'
  }
}
```

**Comment by Goldziher** [comment]
Happy new year 🎊. 

What's your OS / Arch?

> > auto-install-peers=true
> 
> Hi @Goldziher and happy new hear! sorry for bothering and late feedback but also with this (and wasm) doesn't work.
> tested pnpm and npm without success.
> stack is nextjs 16 on macos
> 
> ```
> An error occurred in a function passed to `after()`: Error: Error initializing Kreuzberg WASM module: Cannot find module './kreuzberg_wasm.js'
>     at async (src/server/actions/embeddings/worker.ts:997:7)
>    995 |   after(async () => {
>    996 |     if (DOCUMENTS_PARSER === "kreuzberg") {
> >  997 |       await initWasm();
>        |       ^
>    998 |       await enableOcr();
>    999 |     }
>   1000 |     for (const { id: job_id, document_id: document, document_type } of jobs) { {
>   [cause]: Error: Cannot find module './kreuzberg_wasm.js'
>       at async (src/server/actions/embeddings/worker.ts:997:7)
>      995 |   after(async () => {
>      996 |     if (DOCUMENTS_PARSER === "kreuzberg") {
>   >  997 |       await initWasm();
>          |       ^
>      998 |       await enableOcr();
>      999 |     }
>     1000 |     for (const { id: job_id, document_id: document, document_type } of jobs) { {
>     code: 'MODULE_NOT_FOUND'
>   }
> }
> ```

**Comment by piccinnigius** [comment]
> Happy new year 🎊.
> 
> What's your OS / Arch?
> 
> > > auto-install-peers=true
> > 
> > 
> > Hi [@Goldziher](https://github.com/Goldziher) and happy new hear! sorry for bothering and late feedback but also with this (and wasm) doesn't work.
> > tested pnpm and npm without success.
> > stack is nextjs 16 on macos
> > ```
> > An error occurred in a function passed to `after()`: Error: Error initializing Kreuzberg WASM module: Cannot find module './kreuzberg_wasm.js'
> >     at async (src/server/actions/embeddings/worker.ts:997:7)
> >    995 |   after(async () => {
> >    996 |     if (DOCUMENTS_PARSER === "kreuzberg") {
> > >  997 |       await initWasm();
> >        |       ^
> >    998 |       await enableOcr();
> >    999 |     }
> >   1000 |     for (const { id: job_id, document_id: document, document_type } of jobs) { {
> >   [cause]: Error: Cannot find module './kreuzberg_wasm.js'
> >       at async (src/server/actions/embeddings/worker.ts:997:7)
> >      995 |   after(async () => {
> >      996 |     if (DOCUMENTS_PARSER === "kreuzberg") {
> >   >  997 |       await initWasm();
> >          |       ^
> >      998 |       await enableOcr();
> >      999 |     }
> >     1000 |     for (const { id: job_id, document_id: document, document_type } of jobs) { {
> >     code: 'MODULE_NOT_FOUND'
> >   }
> > }
> > ```

hi, m3 with macos 26.2 from further investigations by running it directly with node in the same repo (and not throught nextjs ts layer) it works.

**Comment by Goldziher** [comment]
> > Happy new year 🎊.
> > 
> > What's your OS / Arch?
> > 
> > > > auto-install-peers=true
> > > 
> > > 
> > > Hi [@Goldziher](https://github.com/Goldziher) and happy new hear! sorry for bothering and late feedback but also with this (and wasm) doesn't work.
> > > tested pnpm and npm without success.
> > > stack is nextjs 16 on macos
> > > ```
> > > An error occurred in a function passed to `after()`: Error: Error initializing Kreuzberg WASM module: Cannot find module './kreuzberg_wasm.js'
> > >     at async (src/server/actions/embeddings/worker.ts:997:7)
> > >    995 |   after(async () => {
> > >    996 |     if (DOCUMENTS_PARSER === "kreuzberg") {
> > > >  997 |       await initWasm();
> > >        |       ^
> > >    998 |       await enableOcr();
> > >    999 |     }
> > >   1000 |     for (const { id: job_id, document_id: document, document_type } of jobs) { {
> > >   [cause]: Error: Cannot find module './kreuzberg_wasm.js'
> > >       at async (src/server/actions/embeddings/worker.ts:997:7)
> > >      995 |   after(async () => {
> > >      996 |     if (DOCUMENTS_PARSER === "kreuzberg") {
> > >   >  997 |       await initWasm();
> > >          |       ^
> > >      998 |       await enableOcr();
> > >      999 |     }
> > >     1000 |     for (const { id: job_id, document_id: document, document_type } of jobs) { {
> > >     code: 'MODULE_NOT_FOUND'
> > >   }
> > > }
> > > ```
> 
> hi, m3 with macos 26.2 from further investigations by running it directly with node in the same repo (and not throught nextjs ts layer) it works.

Great. Can I ask you for a reproduction of the nextjs failure though? I would like to drill down into this

**Comment by Goldziher** [comment]
closing this due to lack of response.
